remote_theme: qwtel/hydejack
title: GitHub Pages, le guide Next INpact
description: Site d'exemple du guide GitHub Pages de Next INpact
author:
 name : David Legrand
defaults:
 -
  scope:
   path: ""
   type: "posts"
  values:
   permalink: /blog/:title
